const modalStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#fff",
    padding: "20px",
    borderRadius: "8px",
    width: "320px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: "4px",
    marginTop: "12px",
  },
  input: {
    width: "100%",
    padding: "10px",
    marginBottom: "10px",
    border: "1px solid #ccc",
    borderRadius: "6px",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  error: {
    color: "red",
    fontSize: "0.85em",
    marginTop: "-6px",
    marginBottom: "10px",
  },
  saveButton: {
    background: "#007bff",
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "4px",
    fontWeight: "bold",
    fontSize: "14px",
    cursor: "pointer",
  },
  cancelButton: {
    marginLeft: "10px",
    background: "#d9d9d9",
    color: "#000",
    border: "none",
    padding: "10px 20px",
    borderRadius: "4px",
    fontWeight: "bold",
    fontSize: "14px",
    cursor: "pointer",
  },
};

export default modalStyles;
